/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trabalhooo;
import trabalhooo.controller.Controller;
import trabalhooo.jogo.Campo;
import trabalhooo.jogo.Fileira;
import trabalhooo.jogo.Jogador;
import trabalhooo.jogo.cartas.Carta;

public class App {
    public static void main(String[] args) {
        try {
           Controller c = new Controller();
           c.inicia();           
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
